### PR TITLE
Create 20.08 branch

### PR DESCRIPTION
**Pull request by A6GibKm**
Merge onto `branch/20.08`.

### CODE REVIEW

**Comment by Erick555** [comment]
I wonder if there are apps that still really need this instead of switching to electron2 baseapp.

**Comment by A6GibKm** [comment]
I wonder the same, but at least minecraft uses it.

**Comment by Erick555** [comment]
Yes minecraft still depends on gtk2 😢

**Comment by joshua-stone** [comment]
@Erick555 @A6GibKm I was able to build io.atom.electron.BaseApp with the 20.08 branch independently and then use it be build [Minecraft](https://github.com/flathub/com.mojang.Minecraft/issues/63) with the newer runtime. Minecraft seems to launch without obvious issues. How much more testing needs to be done?

**Comment by A6GibKm** [comment]
I just made the manifest and tested that at least one app worked without obvious regressions. But I don't quite understand electron well enough to say if this should or should not be merged. Maybe Minecraft should use the electron2 baseapp? Is that even possible?

**Comment by Erick555** [comment]
Last time I checked minecraft still needed gtk2 which means it needs electron baseapp (electron2 is for gtk3).

**Comment by AsciiWolf** [comment]
@TingPing @nedrichards Could this PR please be merged? :-) It is needed to update Minecraft to a newer runtime.

**Pull request merged**
